const GETUSER = 'GETUSER';
const DELETEUSER='DELETEUSER';
const PUTUSER='PUTUSER';
const POSTUSER='POSTUSER'
const SINGLEGETUSER='SINGLEGETUSER'
const VIEWUSER='VIEWUSER'
// const SHOWLOAD='SHOWLOAD'

export{GETUSER,DELETEUSER,PUTUSER,POSTUSER,SINGLEGETUSER,VIEWUSER}