const LOGIN ="LOGIN";
const ALLUSER ="ALLUSER";
const SIGNUP ="SIGNUP";
const CREATE_USER ="CREATE_USER";
const UPDATE_USER ="UPDATE_USER";
const DELETE_USER ="DELETE_USER";
const TOKEN_USER="TOKEN_USER";


export{LOGIN,ALLUSER,SIGNUP,CREATE_USER,UPDATE_USER,DELETE_USER,TOKEN_USER}